exclude = "^(node_modules/)"

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "end-of-file-fixer" },
  { id = "fix-byte-order-marker" },
  { id = "check-json" },
  { id = "check-json5" },
  { id = "check-toml" },
  { id = "mixed-line-ending" },
  { id = "check-symlinks" },
  { id = "check-merge-conflict" },
  { id = "detect-private-key" },
  { id = "check-executables-have-shebangs" },
]

[[repos]]
repo = "local"
[[repos.hooks]]
id = "npm run typecheck"
name = "npm run typecheck"
entry = "npm run typecheck"
language = "system"
pass_filenames = false

[[repos.hooks]]
id = "npm run lint"
name = "npm run lint"
entry = "npm run lint"
language = "system"
pass_filenames = false

[[repos.hooks]]
id = "npm run test"
name = "npm run test"
entry = "npm run test"
language = "system"
pass_filenames = false
